import type { Metadata } from "next";
import "./globals.css";
import { Montserrat } from "next/font/google";
import Footer from "@/components/Footer";
import { headers } from "next/headers";

const montserrat = Montserrat({ subsets: ["latin"], variable: "--font-sans" });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  headers();
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} antialiased `}
      >
        <div className="flex min-h-dvh flex-col">

          <main className="flex-1 items-center justify-center flex">{children}</main>

          <Footer />

        </div>
      </body>
    </html >
  );
}
